# -*- coding: utf-8 -*-
"""bảo sao chỉ tay

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3uLLhhLJ9qcqKYMsSgejBOmNf8euPgE
"""

import os
import random
import zipfile
import shutil
import concurrent.futures
from pathlib import Path
from PIL import Image

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
import numpy as np

# ==============================================================================
# PHẦN 1: CHUẨN BỊ DỮ LIỆU TỐC ĐỘ CAO (ĐA LUỒNG & ĐỔI SANG JPEG)
# ==============================================================================
print("--- BƯỚC 1: XỬ LÝ DỮ LIỆU ---")
zip_path = Path('chi tay dts.zip')
temp_dir = Path('extracted_temp')
out_dir = Path('palmistry_dataset_split')
classes = ['life_long', 'life_short', 'heart_curved', 'heart_straight', 'head_split', 'head_normal']

# Dọn dẹp folder cũ
for d in [temp_dir, out_dir]:
    if d.exists(): shutil.rmtree(d)

for split in ['train', 'test']:
    for cls in classes:
        (out_dir / split / cls).mkdir(parents=True, exist_ok=True)

# Giải nén
print("Đang giải nén file zip...")
with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall(temp_dir)

valid_exts = {'.png', '.jpg', '.jpeg', '.tiff'}
all_imgs = [p for p in temp_dir.rglob('*') if p.suffix.lower() in valid_exts]

random.shuffle(all_imgs)
split_idx = int(len(all_imgs) * 0.8)

splits = {
    'train': all_imgs[:split_idx],
    'test': all_imgs[split_idx:]
}

print(f"Tổng số ảnh quét được: {len(all_imgs)} (TRAIN: {len(splits['train'])} | TEST: {len(splits['test'])})")
print("Đang chạy đa luồng để phân bổ và chuyển đổi sang JPEG cực nhanh. Vui lòng đợi...")

def process_single_image(img_path, split_name, cls_name, index):
    new_name = f"{split_name}_{cls_name}_{index}_{img_path.stem}.jpg"
    dest_path = out_dir / split_name / cls_name / new_name
    try:
        with Image.open(img_path) as img:
            img.convert('RGB').save(dest_path, 'JPEG', quality=95)
    except Exception as e:
        pass

tasks = []
for split_name, img_paths in splits.items():
    for i, img_path in enumerate(img_paths):
        cls_name = classes[i % len(classes)]
        tasks.append((img_path, split_name, cls_name, i))

with concurrent.futures.ThreadPoolExecutor() as executor:
    futures = [executor.submit(process_single_image, *task) for task in tasks]
    concurrent.futures.wait(futures)

shutil.rmtree(temp_dir)
print("✅ Đã hoàn tất xử lý dữ liệu!\n")


# ==============================================================================
# PHẦN 2: HUẤN LUYỆN MÔ HÌNH TRÍ TUỆ NHÂN TẠO (CNN)
# ==============================================================================
# CẦN THÊM IMPORT NÀY Ở ĐẦU (Nếu chưa có)
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.optimizers import Adam

# ==============================================================================
# PHẦN 2: HUẤN LUYỆN MÔ HÌNH TRÍ TUỆ NHÂN TẠO (CNN) - BẢN NÂNG CẤP ĐỘ CHÍNH XÁC
# ==============================================================================
print("--- BƯỚC 2: KHỞI TẠO VÀ HUẤN LUYỆN MÔ HÌNH ---")

img_width, img_height = 200, 200
batch_size = 32

train_dir = out_dir / 'train'
test_dir = out_dir / 'test'

def crop_center(image):
    h, w, c = image.shape
    min_dim = min(h, w)
    start_x = (w // 2) - (min_dim // 2)
    start_y = (h // 2) - (min_dim // 2)
    cropped_image = image[start_y:start_y+min_dim, start_x:start_x+min_dim]
    return tf.image.resize(cropped_image, [img_width, img_height]).numpy()

# ---------------------------------------------------------
# TẠO GENERATORS (Đã giảm nhẹ độ nhiễu để không làm mất đường chỉ tay)
# ---------------------------------------------------------
train_datagen = ImageDataGenerator(
    rescale=1.0/255,
    rotation_range=15,       # Giảm độ xoay
    width_shift_range=0.1,   # Giảm độ xê dịch
    height_shift_range=0.1,
    zoom_range=0.1,          # Giảm độ zoom
    horizontal_flip=True,
    fill_mode="nearest",
    # Đã bỏ channel_shift và brightness để giữ nguyên cấu trúc vân tay
    preprocessing_function=crop_center
)

test_datagen = ImageDataGenerator(
    rescale=1.0/255,
    preprocessing_function=crop_center
)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode="categorical"
)

validation_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode="categorical",
    shuffle=False
)

# ---------------------------------------------------------
# XÂY DỰNG KIẾN TRÚC MÔ HÌNH (Bổ sung Batch Normalization)
# ---------------------------------------------------------
model = Sequential([
    Conv2D(32, (3,3), activation="relu", input_shape=(img_width, img_height, 3)),
    BatchNormalization(), # Giúp mô hình ổn định và học nhanh hơn
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation="relu"),
    BatchNormalization(),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation="relu"),
    BatchNormalization(),
    MaxPooling2D(2,2),

    Conv2D(256, (3,3), activation="relu", padding="same"),
    BatchNormalization(),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(256, activation="relu"),
    BatchNormalization(),
    Dropout(0.5), # Chống học vẹt
    Dense(6, activation="softmax") # 6 Cung chỉ tay
])

# Chỉnh lại tốc độ học (learning rate) nhỏ lại một chút để AI học cẩn thận hơn
optimizer = Adam(learning_rate=0.0005)

model.compile(
    optimizer=optimizer,
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)
model.summary()

# ---------------------------------------------------------

# ---------------------------------------------------------
# Bạn muốn bỏ Early Stopping, nên nó sẽ chạy đủ 100% số Epochs bạn đặt
epochs = 80
history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=epochs
    # Bỏ callbacks=[early_stopping] ở đây
)

# ==============================================================================
# PHẦN 3: ĐÁNH GIÁ, VẼ BIỂU ĐỒ VÀ LƯU MÔ HÌNH
# ==============================================================================
print("\n--- BƯỚC 3: KẾT QUẢ ĐÁNH GIÁ ---")

plt.figure(figsize=(8, 5))
plt.plot(history.history['accuracy'], label="Độ chính xác (Train)")
plt.plot(history.history['val_accuracy'], label="Độ chính xác (Test)")
plt.xlabel("Số vòng học (Epochs)")
plt.ylabel("Độ chính xác")
plt.legend()
plt.title("Lịch sử huấn luyện mô hình Chỉ Tay")
plt.show()

test_loss, test_accuracy = model.evaluate(validation_generator)
print(f"\n=> ĐỘ CHÍNH XÁC THỰC TẾ TRÊN TẬP TEST: {test_accuracy * 100:.2f}%\n")
model_save_path = 'chitay.h5'
model.save(model_save_path)

import tensorflow as tf
import numpy as np
import cv2
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output
import base64
import time
import random
from keras.models import load_model

model = load_model('/content/chitay.h5')

# =====================================================================
# 0. LOAD MÔ HÌNH VÀ TỪ ĐIỂN TIẾNG VIỆT
# =====================================================================

class_names = ['head_normal', 'head_split', 'heart_curved', 'heart_straight', 'life_long', 'life_short']

vn_class_names = {
    'head_normal': 'CUNG LÝ TRÍ THỰC TẾ',
    'head_split': 'CUNG TÂM HỒN ĐA TÌNH',
    'heart_curved': 'CUNG TRÁI TIM LÃNG MẠN',
    'heart_straight': 'CUNG TRÁI TIM KIÊN ĐỊNH',
    'life_long': 'CUNG TÌNH DUYÊN VIÊN MÃN',
    'life_short': 'CUNG TÌNH CẢM THĂNG TRẦM'
}

# =====================================================================
# 1. HÀM TIỀN XỬ LÝ ẢNH (GIỮ NGUYÊN 100%)
# =====================================================================
def preprocess_palm(image_path):
    img = cv2.imread(image_path)
    if img is None: return None

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(5, 5))
    enhanced_gray = clahe.apply(gray)
    blurred = cv2.medianBlur(enhanced_gray, 1)

    _, thresh = cv2.threshold(blurred, 80, 255, cv2.THRESH_BINARY)
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    roi = None
    if contours:
        largest_contour = max(contours, key=cv2.contourArea)
        M = cv2.moments(largest_contour)
        if M["m00"] != 0:
            cX, cY = int(M["m10"] / M["m00"]), int(M["m01"] / M["m00"])
            half_size = 276 // 2
            h, w = blurred.shape

            x1, y1 = max(0, cX - half_size), max(0, cY - half_size)
            x2, y2 = min(w, cX + half_size), min(h, cY + half_size)

            roi = blurred[y1:y2, x1:x2]
            if roi.shape[0] != 276 or roi.shape[1] != 276:
                roi = cv2.resize(roi, (276, 276))

    if roi is None:
        h, w = blurred.shape
        cX, cY = w // 2, h // 2
        roi = blurred[max(0, cY-138):min(h, cY+138), max(0, cX-138):min(w, cX+138)]
        roi = cv2.resize(roi, (276, 276))

    resized_roi = cv2.resize(roi, (138, 138))
    rgb_roi = cv2.cvtColor(resized_roi, cv2.COLOR_GRAY2RGB)
    return rgb_roi


# =====================================================================
# 2. GIAO DIỆN APP (THEME TRẮNG SÁNG TỐI GIẢN - COLAB STYLE)
# =====================================================================
clean_css = """
<style>
.clean-wrapper {
    background-color: #ffffff;
    color: #333333;
    font-family: sans-serif;
    padding: 30px;
    border-radius: 10px;
    border: 1px solid #e0e0e0;
    box-shadow: 0 2px 10px rgba(0,0,0,0.05);
    text-align: center;
    width: 100%;
    box-sizing: border-box;
    margin: 10px 0;
}
.clean-title {
    font-size: 28px;
    font-weight: bold;
    color: #2c3e50;
    margin-bottom: 10px;
    text-transform: uppercase;
}
.clean-subtitle {
    font-size: 16px;
    color: #7f8c8d;
    margin-bottom: 20px;
}
.clean-img {
    max-width: 300px;
    border-radius: 8px;
    border: 1px solid #cccccc;
    margin-bottom: 20px;
}
.clean-result-box {
    background-color: #f8f9fa;
    border: 1px solid #dee2e6;
    border-radius: 8px;
    padding: 25px;
    text-align: left;
    font-size: 16px;
    line-height: 1.6;
    margin-top: 20px;
}
.clean-stats-box {
    background-color: #e9ecef;
    border-left: 4px solid #007bff;
    padding: 15px 20px;
    border-radius: 4px;
    margin-top: 20px;
    font-size: 15px;
}
.clean-footer {
    margin-top: 25px;
    font-size: 14px;
    color: #6c757d;
    font-style: italic;
}
.highlight-text {
    color: #d32f2f;
    font-weight: bold;
    font-size: 18px;
}
hr.clean-hr {
    border: 0;
    height: 1px;
    background-color: #e0e0e0;
    margin: 20px 0;
}
</style>
"""

intro_html = """
<div class='clean-wrapper'>
    <div class='clean-title'>GIẢI MÃ TÌNH DUYÊN & TÍNH CÁCH</div>
    <div class='clean-subtitle'>Khám phá bí ẩn trái tim qua đường chỉ tay của bạn</div>
</div>
"""

btn_layout = widgets.Layout(width='49%', height='40px')
upload_widget = widgets.FileUpload(accept='image/*', multiple=False, layout=btn_layout)
predict_btn = widgets.Button(description='Xem Tình Duyên', button_style='primary', layout=btn_layout)
reset_btn = widgets.Button(description='Tải ảnh khác / Xem Lần Nữa', button_style='info', layout=widgets.Layout(width='100%', height='40px'))
upload_msg = widgets.HTML(value="")

app_container = widgets.Output()
button_hbox = widgets.HBox([upload_widget, predict_btn], layout=widgets.Layout(width='100%', justify_content='space-between'))
button_container = widgets.VBox([button_hbox, upload_msg], layout=widgets.Layout(width='100%', margin='10px 0'))

def render_ui(html_content):
    with app_container:
        clear_output(wait=True)
        display(HTML(clean_css + html_content))

def on_upload_change(change):
    if upload_widget.value:
        upload_msg.value = "<div style='color: #28a745; font-size: 15px; margin-top: 10px; font-weight: bold;'>✅ Đã tải ảnh lên thành công! Nhấn 'Xem Tình Duyên' để tiếp tục.</div>"
    else:
        upload_msg.value = ""

upload_widget.observe(on_upload_change, names='value')

# --- LOGIC NÚT "XEM TÌNH DUYÊN" ---
def on_predict_click(b):
    if not upload_widget.value:
        render_ui("<div class='clean-wrapper'><div class='clean-title' style='color:#dc3545;'>❌ Vui lòng tải ảnh lên trước!</div></div>")
        return

    # HIỆU ỨNG CHỜ
    loading_html = """
    <div class='clean-wrapper'>
        <div class='clean-title'>ĐANG XỬ LÝ...</div>
        <p style='color: #6c757d;'>Hệ thống đang phân tích đường chỉ tay của bạn...</p>
    </div>
    """
    render_ui(loading_html)
    time.sleep(1.5)

    try:
        uploaded_item = list(upload_widget.value.values())[0] if isinstance(upload_widget.value, dict) else upload_widget.value[0]
        img_content = uploaded_item['content'] if isinstance(uploaded_item, dict) else uploaded_item.content

        temp_img_path = 'temp_divination.jpg'
        with open(temp_img_path, 'wb') as f:
            f.write(img_content)

    except Exception as e:
        render_ui(f"<div class='clean-wrapper'>❌ Lỗi hệ thống: {e}</div>")
        return

    roi_img = preprocess_palm(temp_img_path)
    if roi_img is None:
        render_ui("<div class='clean-wrapper'><div class='clean-title' style='color:#dc3545;'>❌ Lỗi: Hình ảnh không rõ ràng.</div></div>")
        return

    img_array = roi_img.astype(np.float32) / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    predictions = model.predict(img_array, verbose=0)

    predicted_index = np.argmax(predictions[0])
    predicted_class = class_names[predicted_index]
    confidence = predictions[0][predicted_index] * 100
    vietnamese_class_name = vn_class_names.get(predicted_class, "Không xác định")

    # Sinh các chỉ số phong thủy ngẫu nhiên
    compat_score = random.randint(82, 98)
    lucky_number = random.randint(11, 99)

    # Lời bình giải
    if predicted_class == 'head_normal':
        divine_text = "Bạn là người yêu thực tế, biết cân bằng giữa cảm xúc và lý trí. Tình yêu của bạn bền vững vì bạn không dễ bị mờ mắt bởi những ảo vọng."
        lucky_color = "Xanh lam (bình yên và vững chãi)"
    elif predicted_class == 'head_split':
        divine_text = "Một tâm hồn nghệ sĩ với trái tim nhiều ngăn. Bạn sáng tạo và cuốn hút, nhưng hãy cẩn thận để không làm lạc mất người thực sự yêu mình nhé."
        lucky_color = "Tím pastel (bay bổng và mộng mơ)"
    elif predicted_class == 'heart_curved':
        divine_text = "Đường chỉ tay này tiết lộ một trái tim nồng cháy, nơi những cung bậc tình cảm được viết nên bởi sự chân thành và những rung cảm sâu sắc. Bạn sinh ra để yêu! Sự ngọt ngào của bạn luôn là điểm tựa ấm áp cho bất kỳ ai bước vào cuộc đời bạn."
        lucky_color = "Đỏ nồng nàn (quyến rũ và lãng mạn)"
    elif predicted_class == 'heart_straight':
        divine_text = "Chung thủy là tôn chỉ của bạn. Khi đã yêu, bạn dành trọn niềm tin. Vũ trụ đang mách bảo rằng lòng kiên định của bạn sẽ sớm được đền đáp."
        lucky_color = "Nâu hoàng thổ (kiên định và son sắt)"
    elif predicted_class == 'life_long':
        divine_text = "Đường tình duyên rộng mở, mọi sóng gió chỉ là thử thách để tình cảm thêm gắn kết. Bạn là người giữ lửa cực kỳ tài ba."
        lucky_color = "Xanh ngọc (viên mãn và thanh tao)"
    elif predicted_class == 'life_short':
        divine_text = "Cảm xúc của bạn như cơn sóng, mãnh liệt và đầy sắc màu. Đừng sợ những thăng trầm, vì chính chúng tạo nên bản tình ca độc nhất cho cuộc đời bạn."
        lucky_color = "Cam (nhiệt huyết và rực rỡ)"
    else:
        divine_text = "Hệ thống đang cần thêm thời gian để phân tích rõ hơn. Hãy thử lại với một bức ảnh khác."
        lucky_color = "Trắng"

    # Xử lý ảnh gốc để hiển thị
    orig_img = cv2.imread(temp_img_path)
    _, buffer = cv2.imencode('.png', cv2.cvtColor(orig_img, cv2.COLOR_RGB2BGR))
    img_b64 = base64.b64encode(buffer).decode('utf-8')

    result_html = f"""
    <div class='clean-wrapper'>
        <div class='clean-title'>KẾT QUẢ PHÂN TÍCH</div>
        <img src='data:image/png;base64,{img_b64}' class='clean-img' alt='Ảnh tay gốc' />

        <div class='clean-result-box'>
            <p><strong>Bản Mệnh:</strong> <span class='highlight-text'>{vietnamese_class_name}</span></p>
            <p><strong>Độ Tin Cậy:</strong> <span>{confidence:.2f}%</span></p>

            <hr class='clean-hr'>

            <p style='text-align: center; font-size: 18px;'><b>LỜI BÌNH GIẢI</b></p>
            <p style='text-align: justify;'>{divine_text}</p>

            <div class='clean-stats-box'>
                <p style='margin: 5px 0;'><strong>Độ hòa hợp:</strong> {compat_score}%</p>
                <p style='margin: 5px 0;'><strong>Màu sắc may mắn:</strong> {lucky_color}</p>
                <p style='margin: 5px 0;'><strong>Con số may mắn:</strong> {lucky_number}</p>
            </div>
        </div>

        <div class='clean-footer'>
            Lưu ý: Kết quả phân tích mang tính chất tham khảo và giải trí.
        </div>
    </div>
    """

    render_ui(result_html)
    button_container.children = [reset_btn]


def on_reset_click(b):
    try:
        upload_widget.value.clear()
    except:
        pass
    upload_msg.value = ""
    render_ui(intro_html)
    button_container.children = [button_hbox, upload_msg]


predict_btn.on_click(on_predict_click)
reset_btn.on_click(on_reset_click)

main_app = widgets.VBox([app_container, button_container], layout=widgets.Layout(width='100%'))
display(main_app)
render_ui(intro_html)